### ISSUE TITLE
Fix glitch on /news page (mobile view) and complete the missing unit tests

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CollegeLutheran#101]
![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/22eea3dc-8912-452a-9bf8-1b45b2b99472)

**Comment by JoshuaVSherman** [comment]
@Unesdala also on the Forum table, please make the Title column width larger so that the text does not wrap, and you can make the Date column a bit smaller (but not wrap), thanks
![image](https://user-images.githubusercontent.com/13340120/74888190-45fbbd80-534b-11ea-9300-190781ee6993.png)

**Comment by JoshuaVSherman** [comment]
@Unesdala also go ahead and make the Forums table scroll vertically within its own container (so we don't have to scroll down the entire page), thanks

**Comment by Unesdala** [comment]
@JoshuaVSherman - Do you have access to the specific styling for that email form over on constant contact or is it done entirely on their end?

**Comment by JoshuaVSherman** [comment]
@JoshuaVSherman it's their end

**Comment by JoshuaVSherman** [comment]
@Unesdala this didn't quite fix it, the word `By` is floating up top of the paragraph below the form, please fix thanks

![image](https://user-images.githubusercontent.com/13340120/75153837-56f55780-56da-11ea-9372-7d7f72ec7212.png)

**Comment by JoshuaVSherman** [comment]
@Unesdala please fix now so that the Dates are not wrapping to 2nd line, thank you
![image](https://user-images.githubusercontent.com/13340120/75153924-8c9a4080-56da-11ea-8ab5-d370d5759ccb.png)

**Comment by Unesdala** [comment]
@JoshuaVSherman What's the resolution you're viewing it on? 320x480 yeah?

**Comment by JoshuaVSherman** [comment]
@Unesdala yes
