### ISSUE TITLE
Nav menu not loading

### ISSUE THREAD

**Issue by Unesdala** [WebJamApps/CollegeLutheran#232]
![Screenshot from 2020-07-18 05-01-36](https://user-images.githubusercontent.com/25317100/87849098-dc5cec80-c8b3-11ea-802a-e44d8823391a.png)

Both in dev, and the current working branch, makeMenuLink isn't being called to create the nav menu.

Have tried with CollegeLutheran, web-jam-back, and WebJamSocketCluster running, CollegeLutheran and WebJamSocketCluster running, CollegeLutheran and web-jam-back running, and solely CollegeLutheran running.

Different pages are still accessible through direct links.

**Comment by JoshuaVSherman** [comment]
@Unesdala please put in a new separate merge request (branch off develop) that is only for fixing this one particular issue please, thank you
