### ISSUE TITLE
Admin dashboard form create a new Youth pic

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CollegeLutheran#43]
* [ ] use name for picture (which would become a caption in the future)
* [ ] url becomes the src for the image, needs to be a direct link, just copy paste from a picture on their facebook page for testing purposes (college lutheran facebook)
* [ ] after new 'book' is created in database, redirect to the youth page, and have the newest picture appear first when the page displays

**Comment by Unesdala** [comment]
@JoshuaVSherman  - What's the POST For youthPics?

**Comment by JoshuaVSherman** [comment]
@Unesdala go look at the other Aurelia project and find the post url there

**Comment by JoshuaVSherman** [comment]
@Unesdala you are posting to `/book` but you need to include the token as a Bearer, ping me if you need further assistance the Aurelia fetch client hides this detail unfortunately, so you need to look up the documentation for using superagent to see how to do this
