### ISSUE TITLE
Fix all jest unit test console errors

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CollegeLutheran#6]
console.error node_modules/prop-types/checkPropTypes.js:20
    Warning: Failed prop type: Invalid prop `homeContent` of type `object` supplied to `WideAboutUs`, expected an array.
        in WideAboutUs
  
  Warning: Failed prop type: Invalid prop `homeContent` of type `object` supplied to `WideAboutUs`, expected an array.
        in WideAboutUs (created by Home)
        in Home (created by Context.Consumer)
        in Route (created by App)
        in Switch (created by App)
        in div (created by AppTemplate)
        in div (created by AppTemplate)
        in div (created by AppTemplate)
        in div (created by AppTemplate)
        in AppTemplate (created by ConnectFunction)
        in ConnectFunction (created by Context.Consumer)
        in withRouter(Connect(AppTemplate)) (created by App)
        in Router (created by BrowserRouter)
        in BrowserRouter (created by App)
        in div (created by App)
        in App (created by ConnectFunction)
        in ConnectFunction
        in PersistGate
        in Provider

  console.error node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: React does not recognize the `allowTransparency` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `allowtransparency` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
        in iframe (created by FacebookFeed)
        in div (created by FacebookFeed)
        in div (created by FacebookFeed)
        in FacebookFeed (created by Home)
        in div (created by Home)
        in div (created by Home)
        in Home (created by Context.Consumer)
        in Route (created by App)
        in Switch (created by App)
        in div (created by AppTemplate)
        in div (created by AppTemplate)
        in div (created by AppTemplate)
        in div (created by AppTemplate)
        in AppTemplate (created by ConnectFunction)
        in ConnectFunction (created by Context.Consumer)
        in withRouter(Connect(AppTemplate)) (created by App)
        in Router (created by BrowserRouter)
        in BrowserRouter (created by App)
        in div (created by App)
        in App (created by ConnectFunction)
        in ConnectFunction
        in PersistGate
        in Provider

**Comment by Unesdala** [comment]
@JoshuaVSherman - This is actually fixed in the latest versions. I patched it up a little bit ago, while bringing tests up to 100% to fix issues that CircleCI was giving me.
