### ISSUE TITLE
Finish unit tests for lib/commonUtils.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CollegeLutheran#86]

**Comment by Unesdala** [comment]
@JoshuaVSherman Do you have any examples of how to do this? Having a hard time figuring out how to start this one.

**Comment by JoshuaVSherman** [comment]
@Unesdala i'm confused by your confusion on this one, just import the commonUtils.js into a new commonUtils.spec.js and test each of the functions as usual, since it is not a React function or component, you don't need shallow, thanks
