### ISSUE TITLE
Fix signup form styling

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CollegeLutheran#87]
also move this to the left a little bit
![image](https://user-images.githubusercontent.com/13340120/95226356-d4358e80-07ca-11eb-8b5d-e540ff352cb3.png)

**Comment by JoshuaVSherman** [comment]
@premdav if you would like to work together on this one, ping me on Slack :)

**Comment by Unesdala** [comment]
@JoshuaVSherman - When you say fix the styling on this, what specifically do you want there?

If it's the form itself, aside from tweaking where it's sitting, I can't do much, given it's being pulled in from an iFrame.

**Comment by JoshuaVSherman** [comment]
Move it a little to the left on page please
