### ISSUE TITLE
Fix the montly forums table to sort by date with the newest one on top

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CollegeLutheran#91]
example of issue

![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/7fc488c9-2dd5-4b9c-a7f5-e51ce5ce5c4f)

**Comment by Unesdala** [comment]
@JoshuaVSherman Isn't that how it's already working in the screenshot you provided? Or do you want them in the reverse order that they're in currently?

Considering the picture is similar to how they are on collegelutheran.com atm.

**Comment by JoshuaVSherman** [comment]
@Unesdala Sorry, my screenshot is not good, just go to www.collegelutheran.org and notice how the January forum with date of 2020-01-05 is after the other forums in the list. What you need to do is sort the array by Date before it gets rendered into the Table, thanks
